# Route mappings for different languages
default_routes:
  /: /
  /docs/: /docs/
  /docs/installation/: /docs/installation/
  /docs/quickstart/: /docs/quickstart/
  /docs/configuration/: /docs/configuration/
  /docs/routing/: /docs/routing/
  /docs/middleware/: /docs/middleware/
  /docs/requests-responses/: /docs/requests-responses/
  /docs/container/: /docs/container/
  /docs/security/: /docs/security/
  /docs/events/: /docs/events/
  /docs/validation/: /docs/validation/
  /docs/database/: /docs/database/
  /docs/providers/: /docs/providers/
  /docs/testing/: /docs/testing/
  /docs/deployment/: /docs/deployment/

pt_routes:
  /: /pt/
  /docs/: /pt/docs/
  /docs/installation/: /pt/docs/instalacao/
  /docs/quickstart/: /pt/docs/inicio-rapido/
  /docs/configuration/: /pt/docs/configuracao/
  /docs/routing/: /pt/docs/roteamento/
  /docs/middleware/: /pt/docs/middleware/
  /docs/requests-responses/: /pt/docs/requisicoes-respostas/
  /docs/container/: /pt/docs/container/
  /docs/security/: /pt/docs/seguranca/
  /docs/events/: /pt/docs/eventos/
  /docs/validation/: /pt/docs/validacao/
  /docs/database/: /pt/docs/banco-de-dados/
  /docs/providers/: /pt/docs/provedores/
  /docs/testing/: /pt/docs/testes/
  /docs/deployment/: /pt/docs/implantacao/